#!/usr/bin/env bash
# installs nginx and configure it to port 80

sudo apt-get update
sudo apt-get -y install nginx
sudo /etc/init.d/nginx restart

sudo echo "Hello World!" > /var/www/html/index.html
