#!/usr/bin/env bash
# Install nginx web server

# Update the package list
sudo apt-get -y update

# Install nginx
sudo apt-get -y install nginx

# Echo "Hello World!" into the default nginx HTML file
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

# Start nginx
sudo service nginx start

