#!/usr/bin/env bash
# Configure Nginx redirection

# Create a backup of the default Nginx configuration file
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# Use sed to replace the location block for /redirect_me with a 301 redirection
sudo sed -i '/^}$/i \ \n\tlocation \/redirect_me { return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4; }' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo service nginx restart

