#!/usr/bin/env bash
#condig the redirection page
if ! command -v nginx &> /dev/null; then
    apt-get update
    apt-get install -y nginx
fi

cat > /etc/nginx/sites-available/redirect_me <<EOF
server {
    listen 80;
    server_name _;
    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
}
EOF
ln -sf /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/redirect_me

nginx -t

service nginx reload

