#!/usr/bin/env bash
#404 page
if ! command -v nginx &> /dev/null; then
    echo "Nginx is not installed. Please install Nginx first."
    exit 1
fi
not_found_page="/var/www/html/404.html"

echo "Ceci n'est pas une page" > "$not_found_page"

sed -i '/server {/r /dev/stdin' /etc/nginx/sites-available/default <<EOF
# Custom 404 page
    error_page 404 /404.html;

    location = /404.html {
        root /usr/share/nginx/html;
        internal;
    }
EOF

service nginx restart

