#!/usr/bin/env bash
#404 page
if ! command -v nginx &> /dev/null; then
    echo "Nginx is not installed. Please install Nginx first."
    exit 1
fi
not_found_page="/var/www/html/404.html"

echo "Ceci n'est pas une page" > "$not_found_page"

sed -i '/server {/a \
    \# Custom 404 page\n\
    error_page 404 /404.html;\n\
    \n\
    location = /404.html {\n\
        root /usr/share/nginx/html;\n\
        internal;\n\
    }\n\
' /etc/nginx/sites-available/default

service nginx restart
