#!/usr/bin/env bash
# Configure Nginx with custom HTTP response header on a new Ubuntu machine

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Configure custom header
custom_header_config=$(cat <<-EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    add_header X-Served-By \$host;
    location / {
        try_files \$uri \$uri/ =404;
    }
    if (\$request_uri ~ /redirect_me){
        rewrite ^ https://th3-gr00t.tk/ permanent;
    }
    error_page 404 /error_404.html;
    location = /error_404.html {
        internal;
    }
}
EOF
)

echo "$custom_header_config" | sudo tee /etc/nginx/sites-enabled/default > /dev/null

# Restart Nginx
sudo service nginx restart

