#!/usr/bin/env bash
# Install and configure HAProxy on lb-01 server

# Install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy
haproxy_config=$(cat <<-EOF
frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 376668-web-01:80 check
    server web-02 376668-web-02:80 check
EOF
)

echo "$haproxy_config" | sudo tee /etc/haproxy/haproxy.cfg > /dev/null

# Restart HAProxy
sudo service haproxy restart
