#!/usr/bin/env bash

# colors
blue='\e[1;34m'
brown='\e[0;33m'
green='\e[1;32m'
reset='\033[0m'

echo -e "${blue}Updating and doing some minor checks...${reset}\n"

function install() {
    command -v "$1" &> /dev/null

    if [ $? -ne 0 ]; then
        echo -e "       Installing: ${brown}$1${reset}\n"
        sudo apt-get update -y -qq && \
        sudo apt-get install -y "$1" -qq
        echo -e "\n"
    else
        echo -e "       ${green}${1} is already installed.${reset}\n"
    fi
}

install haproxy # install haproxy

echo -e "\n${blue}Setting up HAproxy...${reset}\n"

haproxy_config=$(cat <<-EOF
frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 34.224.2.239:80 check
    server web-02 54.90.39.234:80 check
EOF
)

echo "$haproxy_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg

# Restart HAproxy
sudo service haproxy restart

echo -e "\n${green}HAproxy configured successfully.${reset}\n"

