#!/usr/bin/env bash

# Install ufw if not already installed
sudo apt-get update
sudo apt-get install -y ufw

# Set default policies
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allow incoming traffic on specific ports
sudo ufw allow 22/tcp     # Allow SSH
sudo ufw allow 443/tcp    # Allow HTTPS SSL
sudo ufw allow 80/tcp     # Allow HTTP

# Enable ufw
sudo ufw enable

# Display ufw status to confirm the rules
sudo ufw status

