#!/usr/bin/env bash
#test 

sed -i '/user/d' ~/devops_script/copy_nginx_file.txt
sed -i '/worker_process/a user nginx' ~/devops_script/copy_nginx_file.txt
sed -i '/listen/a listen [::]:8080;' ~/devops_script/copy_nginx_file.txt

