#!/usr/bin/env bash
# Stop Nginx service if it's running

systemctl stop nginx

# Update Nginx configuration to run as nginx user
sed -i 's/^user .*/user nginx;/' /etc/nginx/nginx.conf

# Update Nginx configuration to listen on all active IPs on port 8080
sed -i '/^ *listen/ s/$/ default_server;/' /etc/nginx/sites-available/default

# Start Nginx service
systemctl start nginx

